SELECT J.JOB_TITLE AS `Cargo`,
ROUND(AVG(SALARY), 2) AS `Média salarial`,
CASE 
	WHEN AVG(SALARY) >= 2000 AND AVG(SALARY) <= 5800 THEN 'Júnior'
  WHEN AVG(SALARY) >= 5801 AND AVG(SALARY) <= 7500 THEN 'Pleno'
  WHEN AVG(SALARY) >= 7501 AND AVG(SALARY) <= 10500 THEN 'Sênior'
  WHEN AVG(SALARY) > 10500 THEN 'CEO'
  ELSE 'Não Classificado'
END AS `Senioridade`
FROM hr.employees AS E
INNER JOIN hr.jobs AS J
ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
ORDER BY `Média salarial` ASC, `Cargo` ASC; 
