SELECT
  J.JOB_TITLE 'Cargo',
  ROUND(AVG(E.SALARY), 2) 'Média salarial',
  CASE
    WHEN AVG(E.SALARY) BETWEEN 2000 AND 5800 THEN 'Júnior'
    WHEN AVG(E.SALARY) BETWEEN 5801 AND 7500 THEN 'Pleno'
    WHEN AVG(E.SALARY) BETWEEN 7501 AND 10500 THEN 'Sênior'
    WHEN AVG(E.SALARY) > 10500 THEN 'CEO'
  END AS 'Senioridade'
FROM 
  hr.jobs J
    INNER JOIN
  hr.employees E
    ON J.JOB_ID = E.JOB_ID
GROUP BY `Cargo`
ORDER BY `Média Salarial`, `Cargo`;
